'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const pkg=require(path.join(root,'package.json'));
assert.equal(pkg.version,'40.10.0');
assert(html.includes('id="burnOpportunityNotice"'),'aviso de Queima junto à mão ausente');
assert(app.includes("b.className='burn-action-label'"),'botão grande QUEIMAR não foi criado');
assert(app.includes('<strong>QUEIMAR</strong>'),'texto QUEIMAR ausente');
assert(app.includes("el.classList.add('burn-direct')"),'toque direto da Queima de abertura ausente');
assert(app.includes("scrollIntoView({behavior:'smooth'"),'foco automático da carta queimável ausente');
assert(css.includes('.burn-opportunity-notice'),'estilo do aviso de Queima ausente');
assert(css.includes('.burn-action-label'),'estilo do botão grande de Queima ausente');
assert(css.includes('@keyframes burnPulseStrong'),'destaque reforçado da carta queimável ausente');
console.log('✓ V40.10: Queima com aviso, botão grande, destaque e foco automático conferidos.');
