'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const pkg=require(path.join(root,'package.json'));
assert.equal(pkg.version,'40.23.0');
assert(!html.includes('id="burnOpportunityNotice"'),'aviso inferior de Queima ainda está presente');
assert(html.includes('id="floatingBurnBtn"'),'botão flutuante de Queima ausente');
assert(app.includes('triggerFloatingBurn'),'ação do botão flutuante de Queima ausente');
assert(app.includes("el.classList.add('burn-direct')"),'toque direto da Queima de abertura ausente');
assert(app.includes("scrollIntoView({behavior:'smooth'"),'foco automático da carta queimável ausente');
assert(!app.includes("$('#burnOpportunityNotice')"),'lógica do aviso inferior de Queima ainda está presente');
assert(css.includes('.floating-burn-action'),'estilo do botão flutuante de Queima ausente');
assert(css.includes('@keyframes burnPulseStrong'),'destaque reforçado da carta queimável ausente');
console.log('✓ V40.17: Queima sem aviso inferior; destaque, foco e botão flutuante preservados.');
