'use strict';
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const Safety=require('../input-safety');
const pkg=require(path.join(root,'package.json'));
if(!/^40\./.test(pkg.version)) throw new Error('Versão 40.x não aplicada.');
if(!app.includes("canvas.toDataURL('image/webp'")) throw new Error('A figurinha não está sendo convertida para WEBP.');
if(!app.includes('handleCustomAvatarFile')) throw new Error('Fluxo de upload da figurinha não encontrado.');
if(!app.includes('clearCustomAvatarSelection')) throw new Error('Remoção da figurinha personalizada não encontrada.');
if(!app.includes('loadCustomAvatarLocally')) throw new Error('Carregamento local da figurinha não encontrado.');
if(Safety.MAX_CUSTOM_AVATAR_LENGTH!==180000) throw new Error('Limite compatível da figurinha personalizada foi alterado.');
if(!server.includes("InputSafety.cleanAvatar")&&!server.includes('function cleanAvatar(value) { return InputSafety.cleanAvatar(value); }')) throw new Error('Servidor não usa a sanitização compartilhada de avatar.');
console.log('✓ V40.26: upload da figurinha própria preservado.');
