'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const pkg=require(path.join(root,'package.json'));
assert.equal(pkg.version,'40.13.0');
assert(html.includes('id="doubleOpportunityNotice"'),'aviso de Carta Dupla junto à mão ausente');
assert(app.includes("d.className='double-action-label'"),'botão grande ×2 JOGAR DUPLA não foi criado');
assert(app.includes('<strong>JOGAR DUPLA</strong>'),'texto JOGAR DUPLA ausente');
assert(app.includes("el.classList.add('burn-and-double')"),'separação visual entre Queima e Carta Dupla simultâneas ausente');
assert(app.includes("doubleButtonCardIds.has(card.id)"),'controle de um único botão ×2 por par ausente');
assert(app.includes("h.querySelector('.playing-card.double-button-owner')?.scrollIntoView"),'foco automático na carta dona do botão ×2 ausente');
assert(css.includes('.double-opportunity-notice'),'estilo do aviso de Carta Dupla ausente');
assert(css.includes('.double-action-label'),'estilo do botão grande de Carta Dupla ausente');
assert(css.includes('@keyframes doublePulseStrong'),'destaque reforçado da Carta Dupla ausente');
assert(css.includes('.playing-card.double-button-owner'),'prioridade visual da carta dona do botão ×2 ausente');
assert(css.includes('.playing-card.double-mate'),'marcação da segunda cópia sem botão ausente');
assert(css.includes('top:24%!important;height:38px!important'),'posição/área de toque mobile do ×2 não foi melhorada');
console.log('✓ V40.13: um único botão ×2 por dupla, mais alto e maior no celular, com foco correto conferido.');
