'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const pkg=require(path.join(root,'package.json'));
assert.equal(pkg.version,'40.11.0');
assert(html.includes('id="doubleOpportunityNotice"'),'aviso de Carta Dupla junto à mão ausente');
assert(app.includes("d.className='double-action-label'"),'botão grande ×2 JOGAR DUPLA não foi criado');
assert(app.includes('<strong>JOGAR DUPLA</strong>'),'texto JOGAR DUPLA ausente');
assert(app.includes("el.classList.add('burn-and-double')"),'separação visual entre Queima e Carta Dupla simultâneas ausente');
assert(app.includes("h.querySelector('.playing-card.double-available')?.scrollIntoView"),'foco automático da Carta Dupla ausente');
assert(css.includes('.double-opportunity-notice'),'estilo do aviso de Carta Dupla ausente');
assert(css.includes('.double-action-label'),'estilo do botão grande de Carta Dupla ausente');
assert(css.includes('@keyframes doublePulseStrong'),'destaque reforçado da Carta Dupla ausente');
console.log('✓ V40.11: Carta Dupla com aviso, botão grande, destaque, foco automático e coexistência com Queima conferidos.');
