'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const pkg=require(path.join(root,'package.json'));
assert.equal(pkg.version,'40.14.0');
assert(html.includes('id="doubleOpportunityNotice"'),'aviso de Carta Dupla junto à mão ausente');
assert(html.includes('id="floatingDoubleBtn"'),'botão flutuante de Carta Dupla ausente');
assert(app.includes('triggerFloatingDouble'),'ação do botão flutuante de Carta Dupla ausente');
assert(app.includes("el.classList.add('burn-and-double')"),'identificação de Queima e Carta Dupla simultâneas ausente');
assert(app.includes('doubleFocusCardIds'),'controle de foco de uma cópia da dupla ausente');
assert(app.includes("h.querySelector('.playing-card.double-focus-owner')?.scrollIntoView"),'foco automático na Carta Dupla ausente');
assert(css.includes('.double-opportunity-notice'),'estilo do aviso de Carta Dupla ausente');
assert(css.includes('.floating-double-action'),'estilo do botão flutuante de Carta Dupla ausente');
assert(css.includes('@keyframes doublePulseStrong'),'destaque reforçado da Carta Dupla ausente');
assert(css.includes('.playing-card.double-focus-owner'),'prioridade visual da carta focada na dupla ausente');
assert(css.includes('.playing-card.double-mate'),'marcação da segunda cópia sem botão ausente');
assert(css.includes('.floating-game-action{min-width:96px;min-height:42px'),'área de toque mobile dos botões flutuantes ausente');
console.log('✓ V40.14: Carta Dupla com botão flutuante, seleção múltipla e destaque das cartas conferidos.');
