'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const pkg=require(path.join(root,'package.json'));
assert.equal(pkg.version,'40.19.0');
assert(html.includes('id="floatingBurnBtn"'),'botão flutuante de Queima ausente');
assert(html.includes('id="floatingDoubleBtn"'),'botão flutuante de Carta Dupla ausente');
assert(html.includes('id="floatingActionChooser"'),'seletor de múltiplas duplas ausente');
assert(app.includes("const floatingBurnPositionStorage='maumauFloatingBurnPositionV1'"),'persistência da posição da Queima ausente');
assert(app.includes("floatingDoublePositionStorage='maumauFloatingDoublePositionV1'"),'persistência da posição da Dupla ausente');
assert(app.includes("initDraggableGameAction('burn',triggerFloatingBurn)"),'arraste da Queima ausente');
assert(app.includes("initDraggableGameAction('double',triggerFloatingDouble)"),'arraste da Dupla ausente');
assert(app.includes('showDoubleActionChooser(pairs)'),'seleção quando há mais de uma dupla ausente');
assert(app.includes("burnBtn.classList.toggle('hidden',!burnAvailable)"),'Queima não some quando indisponível');
assert(app.includes("doubleBtn.classList.toggle('hidden',!doubleAvailable)"),'Dupla não some quando indisponível');
assert(css.includes('.floating-game-action'),'estilo base flutuante ausente');
assert(css.includes('touch-action:none'),'proteção de arraste/touch ausente');
console.log('✓ V40.15: Queima e Carta Dupla flutuantes, móveis, persistentes e contextuais conferidas.');
