
'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const pkg=require(path.join(root,'package.json'));
assert.equal(pkg.version,'39.1.0');
assert(pkg.dependencies['google-auth-library'],'google-auth-library ausente');
assert(server.includes("app.post('/api/auth/google'"),'endpoint de login Google ausente');
assert(server.includes('verifyIdToken({idToken:credential,audience:GOOGLE_CLIENT_ID})'),'ID token não é validado para o audience correto');
assert(server.includes("const AUTH_COOKIE = 'maumau_google_session'"),'cookie de sessão ausente');
assert(server.includes("'HttpOnly','SameSite=Lax'"),'proteções do cookie ausentes');
assert(server.includes("io.use((socket,next)=>"),'Socket.IO não exige autenticação');
assert(server.includes("playerKey:socket.data.auth.playerKey"),'servidor não controla o playerKey');
assert(server.includes("googlePlayerKey(payload.sub)"),'identidade não deriva do identificador Google');
assert(html.includes('id="authGate"'),'tela obrigatória de login ausente');
assert(html.includes('accounts.google.com/gsi/client'),'Google Identity Services ausente');
assert(!html.toLowerCase().includes('jogar como visitante'),'modo visitante não pode existir');
assert(app.includes('io({autoConnect:false})'),'socket deve aguardar autenticação');
assert(app.includes('initializeGoogleAuth()'),'inicialização da autenticação ausente');
assert(app.includes("fetch('/api/auth/google'"),'cliente não envia credencial ao servidor');
assert(!app.includes("const playerKeyStorage='maumauPlayerKeyV1'"),'playerKey local antigo ainda ativo');
assert(css.includes('V38 — LOGIN GOOGLE OBRIGATÓRIO'),'estilo da tela Google ausente');
console.log('✓ V38: login Google obrigatório, sessão HttpOnly e Socket.IO autenticado conferidos.');
