
'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const pkg=require(path.join(root,'package.json'));
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
assert.strictEqual(pkg.version,'40.58.5');
assert(html.includes('id="localMusicOpen"')&&html.includes('id="localMusicOpen2"'),'atalhos Minha Música ausentes');
assert(html.includes('id="localMusicDialog"')&&html.includes('id="localMusicFile"'),'seletor de música local ausente');
assert(/id="localMusicFile"[^>]+type="file"[^>]+accept="audio\//.test(html),'input não restringe seleção a áudio');
assert(html.includes('id="localMusicAudio"')&&html.includes('controls'),'player local ausente');
assert(app.includes('URL.createObjectURL(file)'),'música local não usa Object URL');
assert(app.includes('URL.revokeObjectURL(localMusicObjectUrl)'),'Object URL não é liberada');
assert(app.includes('liveVoiceActivePlayerIds.size>0'),'música local não considera microfone remoto');
assert(app.includes('liveMicOn'),'música local não considera microfone local');
assert(app.includes("voiceRecorder?.state==='recording'"),'música local não pausa durante gravação de voz');
assert(app.includes('function refreshQuickAudioMusicDuck(){syncLocalMusicVoiceState()}'),'integração voz→pausa ausente');
const start=app.indexOf('// V40.48 — MINHA MÚSICA LOCAL\n// O arquivo escolhido');
const end=app.indexOf('function tone(',start);
assert(start>=0&&end>start,'bloco Minha Música não localizado');
const block=app.slice(start,end);
assert(!block.includes('socket.emit'),'arquivo local não pode ser enviado por Socket.IO');
assert(!block.includes('fetch('),'arquivo local não pode ser enviado por HTTP');
assert(!block.includes('FileReader'),'arquivo local não deve ser convertido em Base64');
assert(!block.includes('localStorage.setItem'),'arquivo da música não deve ser persistido em localStorage');
assert(css.includes('.local-music-modal')&&css.includes('.local-music-file-btn'),'estilos Minha Música ausentes');
assert(!fs.existsSync(path.join(root,'public','assets','music')),'trilhas internas voltaram ao projeto');
console.log('✓ V40.54: Minha Música é local, sem upload, e pausa com voz/microfone.');
