'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const pkg=require(path.join(root,'package.json'));

assert.equal(pkg.version,'40.2.0');
assert(server.includes('const matchmakingQueue = new Map()'),'fila de matchmaking ausente');
assert(server.includes('const MATCHMAKING_WAIT_MS = 15 * 1000'),'janela de 15 s ausente');
assert(server.includes('const MATCHMAKING_MAX_PLAYERS = 5'),'limite de 5 ausente');
assert(server.includes("socket.on('startMatchmaking'"),'entrada na fila ausente');
assert(server.includes("socket.on('cancelMatchmaking'"),'cancelamento da fila ausente');
assert(server.includes('if(matchmakingQueue.has(key))'),'proteção contra fila duplicada ausente');
assert(server.includes('if(matchmakingQueue.size>=MATCHMAKING_MAX_PLAYERS)'),'início imediato com 5 ausente');
assert(server.includes('if(matchmakingQueue.size>=2)scheduleMatchmakingCountdown()'),'contagem após o 2º jogador ausente');
assert(server.includes("Engine.startRound(room)"),'partida automática não inicia rodada');
assert(server.includes("source:'matchmaking'"),'entrada automática na mesa ausente');
assert(server.includes("removeFromMatchmaking(invite.toKey"),'aceitar convite não remove da busca');
assert(server.includes("removeFromMatchmaking(presenceKey"),'queda de conexão não remove da fila');
assert(html.includes('id="matchmakingStart"'),'botão BUSCAR JOGADORES ausente');
assert(html.includes('id="matchmakingDialog"'),'painel de busca ausente');
assert(html.includes('id="matchmakingCancel"'),'botão CANCELAR BUSCA ausente');
assert(app.includes("socket.emit('startMatchmaking'"),'cliente não inicia busca');
assert(app.includes("socket.emit('cancelMatchmaking'"),'cliente não cancela busca');
assert(app.includes("socket.on('matchmakingState'"),'cliente não recebe estado da busca');
assert(app.includes("socket.on('matchmakingMatched'"),'cliente não recebe partida encontrada');
assert(css.includes('.matchmaking-main'),'estilo do botão de busca ausente');
assert(css.includes('.matchmaking-modal'),'estilo do painel de busca ausente');
console.log('✓ V40.2: matchmaking 2–5, janela de 15 s, início imediato com 5 e cancelamento no servidor');
