'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const pkg=require(path.join(root,'package.json'));
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
assert.strictEqual(pkg.version,'40.58.4');
assert(!html.includes('id="musicBtn"')&&!html.includes('id="musicBtnLanding"'),'botão de música interna antiga ainda aparece');
assert(!html.includes('id="musicPanel"'),'painel de música interna ainda aparece');
assert(!app.includes('const musicCatalog='),'catálogo de trilhas internas ainda existe');
assert(!app.includes('maumauMusicOnV1')&&!app.includes('maumauMusicVolumeV1')&&!app.includes('maumauMusicStyleV1'),'preferências legadas de música ainda estão ativas');
assert(!css.includes('.music-panel')&&!css.includes('.landing-music-btn'),'CSS do painel de música ainda existe');
assert(html.includes('id="localMusicOpen"')&&html.includes('id="localMusicOpen2"'),'botões Minha Música ausentes');
assert(html.includes('id="soundBtn"'),'controle de efeitos sonoros foi removido indevidamente');
assert(app.includes("localStorage.setItem('maumauSound'"),'preferência de efeitos sonoros não foi preservada');
assert(app.includes('function beginMusicSpeechDuck(){'),'integração da música local com voz falada ausente');
assert(app.includes('function refreshQuickAudioMusicDuck(){syncLocalMusicVoiceState()}'),'integração da música local com microfone/voz ausente');
console.log('✓ V40.54: sem música interna; Minha Música local + efeitos/voz preservados.');
