'use strict';
const fs=require('fs');
const path=require('path');
const assert=(cond,msg)=>{if(!cond)throw new Error(msg)};
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const workletPath=path.join(root,'public','voice-relay-worklet.js');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));

assert(pkg.version==='40.69.2','package.json deve identificar V40.50');
assert(fs.existsSync(workletPath),'AudioWorklet do relay não foi incluído');
const worklet=fs.readFileSync(workletPath,'utf8');
assert(worklet.includes("registerProcessor('mau-mau-voice-relay-capture'"),'processor AudioWorklet de captura ausente');
assert(worklet.includes('this.port.postMessage')&&worklet.includes('voice-frame'),'AudioWorklet não publica frames de voz');
assert(app.includes('ac.audioWorklet.addModule(LIVE_VOICE_RELAY_WORKLET_URL)'),'app não carrega AudioWorklet');
assert(app.includes("new AudioWorkletNode(ac,'mau-mau-voice-relay-capture'"),'app não instancia AudioWorkletNode');
assert(app.includes('startLiveVoiceRelayScriptFallback'),'fallback compatível para browsers antigos ausente');
assert(app.includes("socket.volatile.emit('liveVoiceRelayPcm'"),'relay de voz deixou de ser volatile');
assert(server.includes("socket.on('networkProbe'"),'sonda de RTT ausente no servidor');
assert(app.includes("socket.timeout(NETWORK_PROBE_TIMEOUT_MS).emit('networkProbe'"),'cliente não mede RTT com timeout');
assert(app.includes('sampleLiveVoiceRtcStats')&&app.includes('pc.getStats()'),'diagnóstico WebRTC ausente');
assert(html.includes('id="networkDiagnosticsDialog"')&&html.includes('id="networkPingValue"'),'painel de diagnóstico ausente');
assert(html.includes('app.js?v=40.69.2')&&html.includes('styles.css?v=40.69.2'),'cache-busting V40.54 ausente');
assert(css.includes('.network-diagnostics-modal')&&css.includes('.quality-warn'),'estilos do diagnóstico ausentes');
console.log('✓ V40.54: AudioWorklet + diagnóstico de conexão e WebRTC conferidos.');
