
'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const pkg=require(path.join(root,'package.json'));
assert.strictEqual(pkg.version,'40.62');
assert(server.includes('pingInterval: 20000')&&server.includes('pingTimeout: 30000'),'heartbeat móvel V40.54 ausente');
assert(server.includes('DISCONNECT_DEBOUNCE_MS = 3000'),'debounce de microqueda ausente');
assert(server.includes('scheduleDisconnectDebounce(ROLE_PLAYER'),'jogador não usa debounce de microqueda');
assert(server.includes('scheduleDisconnectDebounce(ROLE_SPECTATOR'),'observador não usa debounce de microqueda');
assert(app.includes('reconnectionDelay:500')&&app.includes('reconnectionDelayMax:4000')&&app.includes('tryAllTransports:true'),'reconexão rápida/fallback de transporte ausente');
assert(app.includes("socket.volatile.emit('liveVoiceRelayPcm'"),'relay do observador deve ser VOLATILE no cliente');
assert(server.includes(".volatile.emit('liveVoiceRelayPcm'"),'relay do observador deve ser VOLATILE no servidor');
assert(app.includes("LIVE_VOICE_RELAY_CODEC='mulaw8'"),'compressão de voz mulaw8 ausente');
assert(app.includes('LIVE_VOICE_RELAY_VAD_THRESHOLD'),'gate de silêncio do relay ausente');
assert(app.includes('muLaw8FromFloatDownsample'),'encoder de voz leve ausente');
assert(app.includes('muLaw8DecodeSample'),'decoder de voz leve ausente');
assert(!app.includes("socket.emit('liveVoiceRelayPcm',{sampleRate:LIVE_VOICE_RELAY_SAMPLE_RATE,pcm:"),'relay antigo PCM confiável ainda ativo');
assert(html.includes('app.js?v=40.62'),'cache-busting V40.54 ausente');
console.log('✓ V40.54: voz do observador leve/volatile e reconexão móvel reforçada.');
