'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const pkg=require(path.join(root,'package.json'));
assert.equal(pkg.version,'40.2.0');
assert(server.includes('const onlinePresence = new Map()'),'presença online por identidade ausente');
assert(server.includes('const INVITE_TTL_MS = 30 * 1000'),'convite de 30 s ausente');
assert(server.includes('const INVITE_RESERVATION_MS = 20 * 60 * 1000'),'reserva temporária ausente');
assert(server.includes("socket.on('presenceProfile'"),'perfil de presença ausente');
assert(server.includes("socket.on('sendInvite'"),'envio de convite ausente');
assert(server.includes("socket.on('respondInvite'"),'aceitar/recusar convite ausente');
assert(server.includes("socket.on('claimInvite'"),'retomada de convite reservado ausente');
assert(server.includes("i.fromKey===fromKey&&i.toKey===toKey"),'bloqueio de convite duplicado ausente');
assert(server.includes('nowInvite-socket.data.lastInviteAt<900'),'anti-spam de convites ausente');
assert(server.includes("activeMultiplayerRoomForKey(invite.toKey,dest.code)"),'partida multiplayer atual não é preservada');
assert(server.includes("Partida contra a máquina encerrada sem resultado"),'aceite durante bot não trata encerramento sem resultado');
assert(server.includes("room.inviteReservations instanceof Map"),'reserva de vaga no servidor ausente');
assert(html.includes('id="onlinePlayersOpen"'),'botão Jogadores Online na tela inicial ausente');
assert(html.includes('id="onlinePlayersOpen2"'),'acesso Jogadores Online dentro da mesa ausente');
assert(html.includes('id="onlinePlayersDialog"'),'painel Jogadores Online ausente');
assert(html.includes('id="inviteInbox"'),'caixa de convites não bloqueante ausente');
assert(app.includes("socket.on('presenceSnapshot'"),'cliente não recebe presença');
assert(app.includes("socket.on('inviteReceived'"),'cliente não recebe convite');
assert(app.includes("socket.emit('respondInvite'"),'cliente não responde convite');
assert(app.includes("socket.emit('claimInvite'"),'cliente não entra em vaga reservada');
assert(css.includes('.online-players-list'),'estilos da lista online ausentes');
assert(css.includes('.invite-inbox'),'estilos do convite não bloqueante ausentes');
console.log('✓ V40.1: Jogadores Online + Convites, 30 s, reserva e validação no servidor');
