'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const engine=fs.readFileSync(path.join(root,'game-engine.js'),'utf8');
assert(app.includes("type==='opponentMau'"),'som forte opponentMau ausente');
assert(app.includes('function detectOpponentMauMau'),'detecção de adversário com 1 carta ausente');
assert(app.includes('before.cardCount>1'),'transição para 1 carta não está protegida contra repetição');
assert(app.includes('Atenção! ${safeName} está de Mau-Mau! Uma carta!'),'fala de alerta ausente');
assert(app.includes('card-count-badge'),'contador grande não renderizado');
assert(css.includes('.card-count-badge'),'estilo do contador ausente');
assert(css.includes('.card-count-badge.mau-count'),'destaque de 1 carta ausente');
assert(css.includes('.card-count-badge.warning-count'),'destaque de 2 cartas ausente');
assert(html.includes('V23 • 10 AVATARES HD • CONTAGEM VISÍVEL • ALERTA MAU-MAU • MAU-MAU FALADO'),'identificação V23 ausente');
assert(engine.includes('{playerId:p.id,declaration:type}'),'log de Mau-Mau sem identificação estruturada do jogador');
console.log('✓ V23: contador visível e alerta sonoro/falado de adversário em Mau-Mau conferidos.');
