'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const pkg=require(path.join(root,'package.json'));
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
assert.strictEqual(pkg.version,'40.46.0');
assert(app.includes('V40.46 — trilhas longas passam a usar HTMLAudioElement'),'motor musical streaming V40.46 ausente');
const musicBlock=app.slice(app.indexOf('const musicCatalog='),app.indexOf('function tone('));
assert(!musicBlock.includes('decodeAudioData'),'música longa ainda é decodificada inteira na RAM');
assert(!musicBlock.includes('createBufferSource'),'música longa ainda usa AudioBuffer');
assert(musicBlock.includes("audio.preload='metadata'"),'pré-carga de metadados ausente');
assert(musicBlock.includes('musicPlaybackBlocked()'),'bloqueio de música durante microfone/segundo plano ausente');
assert(app.includes('const CUSTOM_AVATAR_MAX_DIMENSION=192'),'figurinha personalizada não foi reduzida para 192px');
assert(app.includes('const CUSTOM_AVATAR_MAX_DATA_URL_LENGTH=90000'),'limite leve da figurinha personalizada ausente');
assert(app.includes('function migrateStoredCustomAvatar()'),'migração de figurinha antiga ausente');
assert(server.includes("stale-while-revalidate=604800"),'cache HTTP de assets ausente');
assert(html.includes('app.js?v=40.46')&&html.includes('styles.css?v=40.46'),'cache-busting V40.46 ausente');
const avatarDir=path.join(root,'public','assets','avatars');
const avatarFiles=fs.readdirSync(avatarDir).filter(x=>x.endsWith('.webp'));
const avatarBytes=avatarFiles.reduce((n,f)=>n+fs.statSync(path.join(avatarDir,f)).size,0);
assert(avatarBytes<350000,`avatares continuam pesados: ${avatarBytes} bytes`);
const landing=path.join(root,'public','assets','music','tela_inicial_instrumental.mp3');
assert(fs.statSync(landing).size<2500000,'música inicial continua acima de 2,5 MB');
const engine=fs.readFileSync(path.join(root,'game-engine.js'),'utf8');
assert(engine.includes("if (ativos.length === 2)"),'regra especial da Dama com 2 jogadores foi alterada');
console.log(`✓ V40.46: streaming musical, cache, avatar leve e figurinha otimizada validados (${avatarBytes} bytes em avatares).`);
