'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('public/index.html');
const app=read('public/app.js');
const css=read('public/styles.css');
const deploy=read('docs/DEPLOY_RENDER.md');
const rules=read('docs/REGRAS.md');

assert(html.includes('Use Google ou e-mail + senha'));
assert(html.includes('minlength="6"')&&html.includes('maxlength="60"'),'senha nova deve permitir 6 a 60 caracteres');
assert(html.includes('googleSignInButton')&&html.includes('emailPasswordAuthBox'));
assert(!/Apple|appleSignInButton|appleid\.cdn-apple\.com/.test(html),'interface não deve exibir Apple');
assert(!/handleAppleLogin|renderAppleSignIn|waitForAppleIdentity/.test(app),'cliente não deve carregar fluxo Apple');
assert(!css.includes('.apple-signin-btn'),'CSS do botão Apple deve ser removido');
assert(!/Apple/i.test(deploy),'guia atual de deploy não deve orientar Apple');
assert(rules.includes('Google ou e-mail + senha'));
console.log('✓ Pré-APK Passo 2B: superfície de login limitada a Google + e-mail/senha.');
