'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const engine=fs.readFileSync(path.join(root,'game-engine.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const pkg=require(path.join(root,'package.json'));
assert.equal(pkg.version,'40.32.0');
assert(server.includes('function buildPublicRoomsSnapshot()'),'snapshot das salas públicas ausente');
assert(server.includes("socket.on('requestPublicRooms'"),'evento para consultar salas públicas ausente');
assert(server.includes("room.isPublic = payload?.publicRoom !== false"),'criação de sala pública não está ligada ao servidor');
assert(server.includes("socket.on('setRoomPublic'"),'anfitrião não consegue mudar visibilidade da sala');
assert(engine.includes('isPublic: false'),'sala não possui flag privada por padrão no motor');
assert(html.includes('id="watchRoomsOpen"'),'botão ASSISTIR PARTIDAS ausente');
assert(html.includes('id="liveRoomsDialog"'),'central de partidas ao vivo ausente');
assert(html.includes('id="publicRoomToggle"'),'controle de sala pública ausente');
assert(html.includes('id="spectatorLivePanel"'),'painel ao vivo do observador ausente');
assert(app.includes("socket.on('publicRoomsSnapshot'"),'cliente não recebe lista de salas públicas');
assert(app.includes("socket.emit('joinSpectator'"),'entrada direta como observador ausente');
assert(app.includes('renderSpectatorLivePanel()'),'painel do observador não é atualizado');
assert(css.includes('.live-rooms-modal'),'estilo da central de partidas ausente');
assert(css.includes('.spectator-live-panel'),'estilo do painel ao vivo ausente');
console.log('✓ V40.32: Central de Partidas ao Vivo, sala pública e painel avançado do observador conferidos.');
