const fs=require('fs');
const path=require('path');
const html=fs.readFileSync(path.join(__dirname,'..','public','index.html'),'utf8');
const app=fs.readFileSync(path.join(__dirname,'..','public','app.js'),'utf8');
const css=fs.readFileSync(path.join(__dirname,'..','public','styles.css'),'utf8');
const server=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');

if(!html.includes('id="quickReactionsWidget"')) throw new Error('Widget flutuante de reações rápidas não encontrado.');
if(!html.includes('id="quickReactionsHandle"')) throw new Error('Alça de arraste das reações rápidas não encontrada.');
if(!html.includes('data-effect="laugh" class="quick-reaction-btn"')) throw new Error('Atalho rápido de risada ausente.');
if(!html.includes('data-effect="angry" class="quick-reaction-btn"')) throw new Error('Atalho rápido de raiva ausente.');
if(!html.includes('data-effect="jogaBoca" class="quick-reaction-btn quick-reaction-speaker"')) throw new Error('Atalho rápido do alto-falante ausente.');
if(!app.includes("const quickReactionsPositionStorage='maumauQuickReactionsPositionV1';")) throw new Error('Storage da posição das reações rápidas não cadastrado.');
if(!app.includes('function initDraggableQuickReactions()')) throw new Error('Lógica de arraste das reações rápidas não implementada.');
if(!app.includes("toast('😂 Reações rápidas voltaram à posição inicial.')")) throw new Error('Reset das reações rápidas por duplo clique não encontrado.');
if(!app.includes("angry:{emoji:'😡',label:'Raiva'}")) throw new Error('Efeito de raiva não cadastrado no app.');
if(!app.includes("effect==='angry'")) throw new Error('Som do efeito de raiva não implementado.');
if(!server.includes("'angry'")) throw new Error('Servidor não permite o efeito de raiva.');
if(!css.includes('.quick-reactions-widget')) throw new Error('CSS do widget flutuante de reações rápidas ausente.');
if(!css.includes('.quick-reactions-handle')) throw new Error('CSS da alça de arraste das reações rápidas ausente.');
console.log('✓ reações rápidas flutuantes V40.19');
