const fs=require('fs');
const path=require('path');
const html=fs.readFileSync(path.join(__dirname,'..','public','index.html'),'utf8');
const app=fs.readFileSync(path.join(__dirname,'..','public','app.js'),'utf8');
const css=fs.readFileSync(path.join(__dirname,'..','public','styles.css'),'utf8');
const server=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');

if(!html.includes('id="quickReactionsWidget"')) throw new Error('Widget flutuante de reações não encontrado.');
if(!html.includes('id="allReactionsBtn"')) throw new Error('Botão da carinha para reações não encontrado.');
if(html.includes('data-effect="laugh" class="quick-reaction-btn"')) throw new Error('Atalho rápido visível de risada ainda está na mesa.');
if(html.includes('data-effect="angry" class="quick-reaction-btn"')) throw new Error('Atalho rápido visível de raiva ainda está na mesa.');
if(html.includes('data-effect="jogaBoca" class="quick-reaction-btn quick-reaction-speaker"')) throw new Error('Atalho rápido visível de alto-falante ainda está na mesa.');
if(!app.includes("const quickReactionsPositionStorage='maumauQuickReactionsPositionV2';")) throw new Error('Storage novo da posição das reações rápidas não cadastrado.');
if(!app.includes('function initDraggableQuickReactions()')) throw new Error('Lógica de arraste das reações rápidas não implementada.');
if(!app.includes("handle.addEventListener('dblclick'")) throw new Error('Duplo clique/duplo toque para resetar a posição não encontrado.');
if(!app.includes("toast('😊 Reações voltaram à posição inicial.')")) throw new Error('Mensagem de reset das reações rápidas não encontrada.');
if(!app.includes("angry:{emoji:'😡',label:'Raiva'}")) throw new Error('Efeito de raiva não cadastrado no app.');
if(!app.includes("toggleAllReactionsPanel()")) throw new Error('Abertura do painel de todas as reações não encontrada.');
if(!server.includes("'angry'")) throw new Error('Servidor não permite o efeito de raiva.');
if(!css.includes('.quick-reactions-widget-minimal')) throw new Error('CSS do modo minimalista das reações rápidas ausente.');
if(!css.includes('.quick-reaction-main')) throw new Error('CSS do botão principal de reações ausente.');
console.log('✓ reações rápidas minimalistas V40.22');
