'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const pkg=require(path.join(root,'package.json'));
assert.equal(pkg.version,'39.1.0');
assert(/RECONNECT_GRACE_MS\s*=\s*60\s*\*\s*1000/.test(server),'janela de 60 s ausente');
assert(server.includes('scheduleReconnectTakeover'),'takeover temporário ausente');
assert(server.includes('stale.autoControlled=true'),'vaga não entra em AUTO');
assert(server.includes('wasAutoControlled'),'retomada do humano ausente');
assert(server.includes('roomWaitingForReconnect'),'pausa real do servidor ausente');
assert(server.includes('requireRoundNotPaused(room)'),'ações não estão protegidas durante pausa');
assert(server.includes('if (!room.players.some(p => !p.isBot && p.connected)) return;'),'mesa não deve se jogar sozinha sem humanos presentes');
assert(app.includes('function reconnectBannerText()'),'contagem regressiva visual ausente');
assert(app.includes('data-deadline'),'badge de reconexão ausente');
assert(app.includes("event?.kind==='returned-from-auto'"),'feedback de retomada ausente');
assert(css.includes('.player-card.auto-control'),'estilo AUTO ausente');
assert(html.includes('Reconexão Inteligente'),'regra visível de reconexão ausente');
console.log('✓ V39.1: contrato de Reconexão Inteligente aprovado');
