'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const Engine=require('../game-engine');
const {plainRoomSnapshot,restoreRoomSnapshot}=require('../room-snapshot-store');
const pkg=require('../package.json');

assert.strictEqual(pkg.version,'40.58.4');
const room=Engine.createRoom('ABCD',{socketId:'sock-host',token:'tok-host',name:'Host',avatar:'macaco',playerKey:'g_host'});
Engine.addPlayer(room,{socketId:'sock-2',token:'tok-2',name:'Dois',avatar:'data:image/webp;base64,AAAA',playerKey:'g_2'});
room.status='playing';room.round=2;room.currentPlayer=1;room.players[0].hand=[{id:'c1',rank:'5',suit:'clubs',copy:1}];room.players[1].hand=[{id:'c2',rank:'A',suit:'spades',copy:1}];
room.spectators=[{id:'s1',socketId:'spec',connected:true,name:'Obs'}];
room.inviteReservations=new Map([['g_x',{expiresAt:Date.now()+10000}]]);
room.botTimer=setTimeout(()=>{},10000);
const snapshot=plainRoomSnapshot(room);clearTimeout(room.botTimer);
assert(snapshot,'snapshot ausente');
assert(!('botTimer' in snapshot),'timer não deve ser serializado');
assert.deepStrictEqual(snapshot.spectators,[],'observadores devem continuar efêmeros');
assert(snapshot.players.every(p=>p.socketId===null),'socketId não deve ser persistido');
const now=1700000000000;
const restored=restoreRoomSnapshot(snapshot,{now,reconnectGraceMs:60000});
assert(restored&&restored.code==='ABCD');
assert.strictEqual(restored.status,'playing');assert.strictEqual(restored.round,2);assert.strictEqual(restored.currentPlayer,1);
assert.deepStrictEqual(restored.players[0].hand,room.players[0].hand,'mão precisa sobreviver ao snapshot');
assert.deepStrictEqual(restored.players[1].hand,room.players[1].hand,'mão precisa sobreviver ao snapshot');
assert(restored.players.filter(p=>!p.isBot).every(p=>!p.connected&&p.socketId===null),'humanos restaurados devem aguardar reconexão');
assert(restored.players.filter(p=>!p.isBot).every(p=>p.reconnectDeadlineAt===now+60000),'nova janela de 60s ausente');
assert(restored.inviteReservations instanceof Map,'reservas efêmeras devem reiniciar como Map');
const server=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');
assert(server.includes("process.once('SIGTERM'")&&server.includes('flushAll(rooms)'),'shutdown gracioso/snapshot final ausente');
assert(server.includes('restorePersistedRooms')&&server.includes('roomSnapshotStore.loadActive'),'restauração no boot ausente');
assert(server.includes('roomSnapshotStore.queueSave(room)'),'persistência após atualização de sala ausente');
console.log('✓ V40.54: snapshot/restauração de sala, janela de reconexão e SIGTERM conferidos.');
