const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync('public/index.html','utf8');
const css=fs.readFileSync('public/styles.css','utf8');
const app=fs.readFileSync('public/app.js','utf8');
const mic=html.indexOf('id="liveMicBtn"');
const main=html.indexOf('<main class="table-shell">');
const felt=html.indexOf('<div class="felt">');
assert(mic>0,'botão liveMicBtn deve existir');
assert(mic<main,'microfone deve ficar fora da table-shell/felt para não ser recortado');
assert(mic<felt,'microfone não pode ser filho visual do felt com overflow hidden');
assert(css.includes('#game.spectator-mode #liveMicBtn.live-mic-btn'),'CSS deve garantir microfone visível no Modo Observador');
assert(css.includes('display:inline-flex!important'),'CSS deve forçar exibição do microfone no Modo Observador');
assert(app.includes('liveMicSpectatorPositionStorage'),'observador deve ter posição própria do microfone');
assert(app.includes('ensureLiveMicRolePosition()'),'UI deve reposicionar microfone ao trocar entre jogador e observador');
assert(app.includes("btn.classList.remove('hidden')"),'updateLiveMicUI deve remover hidden');
console.log('✅ V40.35: microfone do observador fica fora do felt, visível e com posição própria');
