'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const pkg=require(path.join(root,'package.json'));
assert.equal(pkg.version,'40.32.0');
assert(html.includes('id="spectatorOfferDialog"'),'diálogo de entrada como observador ausente');
assert(html.includes('👁️ ASSISTIR PARTIDA'),'botão ASSISTIR PARTIDA ausente');
assert(html.includes('id="spectatorModeBanner"'),'faixa MODO OBSERVADOR ausente');
assert(app.includes("socket.on('spectatorOffer'"),'cliente não escuta oferta de observador');
assert(app.includes("socket.emit('joinSpectator'"),'cliente não solicita entrada como observador');
assert(app.includes("sess.role==='SPECTATOR'"),'reconexão do navegador não preserva papel de observador');
assert(app.includes("$('#handPanel')?.classList.toggle('hidden',spectator)"),'mão não é removida da interface do observador');
assert(app.includes("observerTag=m.role==='SPECTATOR'"),'chat não identifica observadores');
assert(css.includes('.spectator-mode-banner'),'estilo do Modo Observador ausente');
assert(css.includes('.spectator-chat-tag'),'estilo da identificação do observador no chat ausente');
console.log('✓ V40.31: interface de entrada, faixa de observador, chat e reconexão conferidas.');
