'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const pkg=require(path.join(root,'package.json'));

assert.ok(/^40\./.test(pkg.version));
assert(app.includes('LIVE_VOICE_RELAY_SAMPLE_RATE=16000'),'fallback deve manter voz mono 16 kHz');
assert(app.includes("socket.volatile.emit('liveVoiceRelayPcm'"),'fallback do cliente deve permanecer volatile');
assert(app.includes("socket.on('liveVoiceRelayPcm',playLiveVoiceRelayPcm)"),'cliente não reproduz fallback de voz');
assert(!app.includes("if(isSpectatorState()||peer?.role==='SPECTATOR')return"),'V40.53 ainda bloqueia WebRTC para observador');
assert(app.includes('liveVoiceRelayFallbackPeers'),'fallback seletivo por peer ausente');
assert(app.includes('targetSocketIds:liveVoiceRelayTargets()'),'cliente não direciona fallback apenas aos peers problemáticos');
assert(app.includes('healthyInboundLiveVoiceFrom'),'proteção contra duplicação WebRTC + fallback ausente');
assert(server.includes('requestedTargets'),'servidor não valida alvos seletivos do fallback');
assert(server.includes('currentVoiceSocketInRoom(room.code,targetSocketId)'),'servidor não restringe fallback à própria sala');
assert(server.includes('pcm.length>16000'),'fallback não limita tamanho dos pacotes');
assert(app.includes("LIVE_VOICE_RELAY_CODEC='mulaw8'"),'fallback leve mulaw8 ausente');
assert(server.includes('liveVoiceRelayAllowed'),'fallback não possui limite de taxa');
console.log('✓ V40.53: observadores usam WebRTC/Opus primeiro e relay leve somente como fallback seletivo.');
