'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const engine=fs.readFileSync(path.join(root,'game-engine.js'),'utf8');
assert(server.includes("const ROLE_PLAYER = 'PLAYER'"),'papel PLAYER ausente');
assert(server.includes("const ROLE_SPECTATOR = 'SPECTATOR'"),'papel SPECTATOR ausente');
assert(server.includes("socket.on('joinSpectator'"),'evento joinSpectator ausente');
assert(server.includes("socket.emit('spectatorOffer'"),'oferta ASSISTIR não é emitida pelo servidor');
assert(server.includes('room.spectators'),'observadores não estão separados da lista de jogadores');
assert(server.includes("socket.data.role === ROLE_SPECTATOR")||server.includes("socket.data.role===ROLE_SPECTATOR"),'bloqueio de ações para observador ausente');
assert(server.includes('socialActorForSocket'),'chat/reações não reconhecem observador');
assert(server.includes('scheduleSpectatorRemoval'),'reconexão do observador não está preservada');
assert(engine.includes('function roomSpectatorState'),'estado seguro do observador ausente');
assert(server.includes("Saia do Modo Observador antes de criar outra sala."),'observador deve sair antes de assumir outro papel no mesmo socket');
assert(server.includes("if(room.status==='playing'||lateJoinClosed)"),'entrada manual em partida já iniciada deve oferecer Modo Observador');
assert(engine.includes('function spectatorPublicLog'),'filtro de log derivado da mão ausente');
assert(engine.includes("viewerRole: 'SPECTATOR'"),'estado do observador não identifica SPECTATOR');
assert(engine.includes('hand: []'),'estado do observador precisa ter mão vazia local');
console.log('✓ V40.31: contrato servidor PLAYER/SPECTATOR, reconexão, chat e proteção de ações conferidos.');
