'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const engine=fs.readFileSync(path.join(root,'game-engine.js'),'utf8');

assert(app.includes('quickActionCardIds'),'cliente precisa receber oportunidades de Ação Rápida');
assert(app.includes("socket.emit('quickAction'"),'cliente precisa enviar Ação Rápida ao servidor');
assert(app.includes("q.textContent='⚡'"),'botão ⚡ precisa existir na carta');
assert(app.includes('doubleByCard'),'Carta Dupla deve mapear as duas cópias');
assert(app.includes('doubleButtonCardIds'),'Carta Dupla deve escolher uma única cópia para receber o botão ×2');
assert(css.includes('.quick-btn'),'CSS do botão de Ação Rápida ausente');
assert(css.includes('.playing-card.quickable'),'destaque visual da Ação Rápida ausente');
assert(server.includes("socket.on('quickAction'"),'servidor precisa ouvir Ação Rápida');
assert(engine.includes('function canQuickAction'),'motor precisa detectar Ação Rápida');
assert(engine.includes('function quickAction'),'motor precisa executar Ação Rápida');
assert(html.includes('AÇÃO RÁPIDA') || html.includes('Ação Rápida'),'regras visuais precisam explicar Ação Rápida');
assert(html.includes('>VER REGRAS<'),'atalho de regras deve usar somente o texto VER REGRAS');
assert(!html.includes('Ver regras desta versão'),'atalho de regras não deve exibir texto técnico de versão');
assert(html.includes('Queima — própria vez + primeira carta da rodada'),'regras visuais devem explicar a Queima normal e a exceção da abertura');
assert(html.includes('Exceção da abertura'),'regras visuais devem explicar que a primeira carta pode ser queimada fora da vez');
assert(app.includes('burnMustDraw'),'cliente precisa distinguir quando a compra é obrigatória após a queima');
assert(app.includes('canPassBurn'),'cliente precisa permitir passar após a queima');
assert(engine.includes('Depois da queima você já possui carta compatível'),'motor deve bloquear compra desnecessária após a queima');
assert(engine.includes('passou a vez após a queima'),'motor deve registrar passe após queima');
console.log('✓ UI/servidor: Queima Flexível, Ação Rápida e Carta Dupla com botão único conferidas.');
