'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const worklet=fs.readFileSync(path.join(root,'public','voice-relay-worklet.js'),'utf8');
assert(html.includes('app.js?v=40.69.2-v49.11-mic-stability-phase1'),'cache-busting V49.11 ausente');
assert(server.includes("const UI_VERSION = '49.11'"),'UI_VERSION V49.11 ausente');
assert(app.includes('restartOutboundLiveVoiceIce')&&app.includes('pc.restartIce')&&app.includes('iceRestart:true'),'ICE restart real ausente');
assert(server.includes("if(kind==='offer'&&payload?.iceRestart===true)out.iceRestart=true"),'servidor não preserva marca de ICE restart');
assert(app.includes('if(msg?.iceRestart&&existing'),'receiver deve reaproveitar peer somente no ICE restart');
assert(app.includes("firstDisconnected?2400"),'disconnected deve ter tolerância antes do reparo');
assert(app.includes("socket.emit('liveVoiceRefreshPeer'"),'refresh dirigido por peer ausente');
assert(server.includes("socket.on('liveVoiceRefreshPeer'"),'servidor não recebe refresh dirigido');
assert(server.includes('liveVoiceTargetRefreshAllowed'),'throttle por par ausente');
assert(app.includes('closeOtherInboundLivePeers(from,key)'),'deduplicação inbound por socket ausente');
assert(app.includes('liveVoiceInboundRtpHealth')&&app.includes('bytesReceived'),'saúde RTP inbound ausente');
assert(app.includes('inboundLiveVoiceConnectionHealthyFrom'),'retomada geral não pode confundir silêncio com falha RTP');
assert(app.includes('targetDelay:.11')&&app.includes('Math.min(.26'),'jitter buffer adaptativo do relay ausente');
assert(worklet.includes('this.preRollFrame')&&worklet.includes('preroll: true'),'pré-roll do VAD ausente');
assert(app.includes("LIVE_VOICE_RELAY_WORKLET_URL='voice-relay-worklet.js?v=49.11'"),'cache do worklet V49.11 ausente');
assert(!app.includes("liveVoiceInboundRefreshAt=0"),'throttle inbound global antigo ainda ativo');
console.log('✓ V49.11: recuperação por peer, ICE restart, deduplicação, RTP health, jitter adaptativo e pré-roll validados.');
