'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');

assert(/app\.js\?v=40\.69\.2-v49\.(10-mic-stability|11-mic-stability-phase1)/.test(html),'cache-busting compatível V49.10/V49.11 ausente');
assert(/const UI_VERSION = '49\.(10|11)'/.test(server),'UI_VERSION V49.10/V49.11 ausente');
assert(app.includes('liveVoiceConfigExpiresAt'),'cache de TURN não possui expiração');
assert(app.includes('ttlSeconds*800'),'credenciais TURN temporárias não são renovadas antes do vencimento');
assert(app.includes('invalidateLiveVoiceRtcConfig'),'invalidação de ICE/TURN ausente');
assert(app.includes("liveVoiceNetworkConnection?.addEventListener?.('change'"),'troca de rede não dispara recuperação de voz');
assert(app.includes("scheduleLiveVoiceTransportRecovery('online'"),'retorno online não recupera transporte de voz');
assert(app.includes("scheduleLiveVoiceTransportRecovery('visible'"),'retorno do segundo plano não recupera transporte de voz');
assert(app.includes('resumeLiveVoicePlayback'),'retomada de reprodução após segundo plano ausente');
assert(app.includes("requestLiveVoiceInboundRefresh(from,'inbound-recovery')"),'receptor não pede recuperação dirigida quando o WebRTC falha');
assert(app.includes("socket.emit('liveVoiceRefreshPeer'"),'pedido dirigido de reconstrução inbound ausente');
assert(app.includes("socket.emit('liveVoiceJoin');"),'remetente não reafirma voz após recuperação');
assert(app.includes("startLiveMic({recovery:true,reason})"),'reinício automático de captura ausente');
assert(app.includes('if(!liveMicWanted||liveMicOn||liveMicRestartTimer)return;'),'retry de captura não deve ser bloqueado pelo estado liveMicStarting durante o catch');
assert(app.includes("track.onended=()=>"),'fim inesperado da trilha do microfone não é tratado');
assert(app.includes('setLiveVoiceRelayFallback(socketId,true)'),'fallback seletivo precisa permanecer ativo durante recuperação');
assert(server.includes('liveVoiceTargetRefreshAllowed'),'servidor não limita pedidos dirigidos de reconstrução da voz');
assert(server.includes('refresh:true')&&server.includes('notifyLiveVoiceSenderToRefresh'),'servidor não sinaliza refresh dirigido para o remetente');
assert(app.includes('peer?.refresh&&liveMicOutboundPeers.has(socketId)')&&app.includes('restartOutboundLiveVoiceIce'),'remetente não tenta ICE restart a pedido do receptor');
console.log('✓ V49.10/V49.11: estabilidade do microfone preservada e recuperação dirigida validada.');
