'use strict';
const fs=require('fs');
const path=require('path');
const vm=require('vm');
const src=fs.readFileSync(path.join(__dirname,'..','public','app.js'),'utf8');
const start=src.indexOf('function newLogEntries(prev,next)');
const end=src.indexOf('function triggerYourTurnCue()',start);
if(start<0||end<0)throw new Error('helpers de SUA VEZ não encontrados');
const ctx={};vm.createContext(ctx);vm.runInContext(src.slice(start,end),ctx);
const me={id:'p1',hand:[{id:'a'},{id:'b'}]};
const playing={status:'playing',paused:false,currentPlayerId:'p1',me,players:[{id:'p1',cardCount:2}],log:[]};
if(!ctx.shouldCueMyTurn(null,playing))throw new Error('entrada inicial na própria vez deve alertar');
const fromOpponent={...playing,currentPlayerId:'p2'};
if(!ctx.shouldCueMyTurn(fromOpponent,playing))throw new Error('mudança de adversário para mim deve alertar');
const paused={...playing,paused:true};
if(!ctx.shouldCueMyTurn(paused,playing))throw new Error('retomada após pausa deve alertar');
const afterDraw={...playing,me:{...me,hand:[{id:'a'},{id:'b'},{id:'c'}]}};
if(ctx.shouldCueMyTurn(playing,afterDraw))throw new Error('compra durante a mesma vez não pode repetir o alerta');
const beforeQ={...playing,me:{...me,hand:[{id:'a'},{id:'b'}]},log:[{id:'1',kind:'turn',message:'Ana joga.'}]};
const afterQ={...playing,me:{...me,hand:[{id:'b'}]},log:[{id:'1',kind:'turn',message:'Ana joga.'},{id:'2',kind:'special',message:'A Dama inverteu o sentido e, com 2 jogadores, Ana joga novamente.'}]};
if(!ctx.shouldCueMyTurn(beforeQ,afterQ))throw new Error('Dama com 2 jogadores deve gerar nova SUA VEZ');
const quickSame={...playing,log:[{id:'3',kind:'quick',message:'Outro fez AÇÃO RÁPIDA.'}]};
if(ctx.shouldCueMyTurn(playing,quickSame))throw new Error('Ação Rápida de terceiro não deve repetir SUA VEZ');
console.log('✓ V39.2: lógica de disparo de SUA VEZ validada');
