'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const pkg=require(path.join(root,'package.json'));

assert.ok(['40.33.0','40.34.0'].includes(pkg.version));
assert(app.includes('liveMicCandidateQueues=new Map()'),'fila de candidatos ICE ausente');
assert(app.includes('queueLiveVoiceCandidate'),'fila ICE não implementada');
assert(app.includes('flushLiveVoiceCandidates'),'candidatos ICE não são liberados após descrição remota');
assert(app.includes('scheduleOutboundLiveVoiceRecovery'),'recuperação automática de conexão ausente');
assert(app.includes('liveMicRetryTimers'),'temporizador de recuperação de voz ausente');
assert(app.includes("window.addEventListener('online'"),'retomada após retorno da rede ausente');
assert(app.includes('keepWanted:liveMicWanted'),'microfone não preserva intenção durante reconexão Socket.IO');
assert(app.includes("track.contentHint='speech'"),'contentHint de voz ausente');
assert(app.includes('maxBitrate=48000'),'limite de bitrate de voz ausente');
assert(app.includes("getCapabilities?.('audio')"),'seleção de codec de áudio ausente');
assert(app.includes("audio/opus"),'preferência por Opus ausente');
assert(app.includes('channelCount={ideal:1}'),'captura mono ausente');
assert(app.includes('sampleRate={ideal:48000}'),'sample rate de voz ausente');
assert(app.includes("fetch('/api/voice/config'"),'configuração ICE dinâmica ausente');
assert(server.includes("app.get('/api/voice/config'"),'endpoint de configuração ICE ausente');
assert(server.includes('VOICE_TURN_URLS'),'TURN opcional não suportado');
assert(server.includes('VOICE_TURN_USERNAME')&&server.includes('VOICE_TURN_CREDENTIAL'),'credenciais TURN não suportadas');
assert(server.includes("Cache-Control','no-store"),'configuração TURN deve evitar cache');
assert(css.includes('.live-mic-btn.mic-reconnecting'),'estado visual de reconexão ausente');
console.log('✓ V40.33: fila ICE, Opus, reconexão automática e TURN opcional conferidos.');
